services:
  observer:
    image: hashgraph-observer
    networks:
      - mynetwork
    volumes:
      - ./observer/images:/usr/hashgraph-observer/images
    hostname: "observer"
    command: -id 4

  alpha:
    image: hashgraph-node
    networks:
      - mynetwork
    hostname: "alpha"
    command: -id 0

  bravo:
    image: hashgraph-node
    networks:
      - mynetwork
    hostname: "bravo"
    command: -id 1

  charlie:
    image: hashgraph-node
    networks:
      - mynetwork
    hostname: "charlie"
    command: -id 2

  delta:
    image: hashgraph-node
    networks:
      - mynetwork
    hostname: "delta"
    command: -id 3

networks:
  # The presence of these objects is sufficient to define them
  mynetwork: {}
